# Generated by Django 5.1.3 on 2024-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('joke', models.TextField(blank=True, null=True)),
                ('flags_nsfw', models.BooleanField()),
                ('flags_political', models.BooleanField()),
                ('flags_sexist', models.BooleanField()),
                ('safe', models.BooleanField()),
                ('lang', models.CharField(max_length=10)),
            ],
        ),
    ]
